### ISSUE TITLE
back() function contains new question

### ISSUE THREAD

**Issue by kingmigdor** [NinjaSnail1080/akinator.py#20]
I am using the library for my discord bot. That means more than one session has to be opened. But now sometimes the "akinator.back()" function returns a new question instead of an old one.

**Comment by NinjaSnail1080** [comment]
That is really weird. Does your bot create new instances of the Akinator class? Cause calling start_game more than once on the same instance just resets it

**Comment by kingmigdor** [comment]
`class Aki(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @commands.command(aliases = ['aki'])
    async def akinator(self, ctx):

        global aki
        with suppress(akinator.AkiTimedOut):
            aki = Akinator()
            question = await aki.start_game(language = 'de')`
            
 I am calling the Akinator() class every time the command has been called. So it should create a new instance, shouldn't it?

**Comment by NinjaSnail1080** [comment]
I believe the line `global aki` is causing the problem. Since `aki` is a global variable, `aki` is reassigned to a new Akinator instance every time the command is called. So it does create a new instance, but it also causes everyone currently playing an akinator game to switch to the new instance.

Here's how you can test this:

1. Run the akinator command (game 1)
2. Answer a few questions in game 1
3. Go to a different channel and run the command again (game 2)
4. Answer one question in game 2
5. Go back to game 1 and use the back command. It should now show whatever the first question in game 2 was since the aki variable was reassigned to game 2's Akinator class

Removing the `global aki` line should fix this. It'll make `aki` a local variable to the function, so it'll create a new instance whenever it's called without affecting the previous instances.
